### ISSUE TITLE
Hang after running all tests

### ISSUE THREAD

**Issue by ozjongwon** [gar3thjon3s/lein-expectations#11]
Currently I have this hang problem and have absolutely no idea.
I run 'lein expectations' at command line.

Could anyone tell me in what circumstances expectation hanging without quitting? 

Thx!

**Comment by seancorfield** [comment]
The most likely cause is something in one of your namespaces -- or something loaded by one of your namespaces -- is creating a thread pool that is not being shut down properly. This is not a bug in `lein-expectations` or Expectations, however. Your best bet is to narrow this down to either a particular test that triggers the problem and ask for help by sharing that code on either the Clojure mailing list or the Clojurians Slack.

**Comment by ozjongwon** [comment]
Is there any hook to call after running all tests? Like "after-run" ?

**Comment by seancorfield** [comment]
Currently no. There's `in-context` to run setup/teardown around each test, for all tests, and there's `before-run` to run setup before the entire suite runs.

**Comment by ozjongwon** [comment]
I looked at the expectations code and there is actually after-run hook, so
I wrote a shutdown function, ran a quick run and it worked.

I believe the feature is already there, but it's undocumented.

Thx

**Comment by seancorfield** [comment]
Good to know! I'll have to take a look at that and update the documentation accordingly. Thank you. Glad you got your tests working.

**Comment by seancorfield** [comment]
https://github.com/clojure-expectations/clojure-expectations.github.io/issues/3
